seed: 0
device: "cuda"

data:
  num_symbols: 50
  array_len: 100
  num_steps: 1_000
  batch_size: 1_000

model:
  embedding_dim: 1024

optimizer:
  learning_rate: 0.01
  weight_decay: 0.0001
  beta_1: 0.9
  beta_2: 0.999
  grad_clip: 1.0

eval:
  num_samples: 1_000

log:
  log_every: 1
  eval_every: 1
  save_every: 1


# disable Hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# disable Hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
